Algoritmo "Concatenação"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 03/05/2020
Var
// Seção de Declarações das variáveis
// Concatenação
    nome: caracter
    numero: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
    escreval("Digite o nome: ")
    leia(nome)
    escreval("Digite o número: ")
    leia(numero)
    
    escreval(nome, " :", numero)

Fimalgoritmo