Algoritmo "Conversão de temperatura"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 03/05/2020
Var
// Seção de Declarações das variáveis 
c, f: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva("Informe a temperatura C: ")
leia(c)
f <- (9*c+160)/5
escreval() // pula uma linha
escreval("A temperatura em F é ",f)

Fimalgoritmo