Algoritmo "Operadores relacionais"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 03/05/2020
Var
// Seção de Declarações das variáveis 
    nota1, nota2: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
// Operadores relacionais
    nota1 := 10
    nota2 := 15

    se nota1 <> nota2 entao
        escreval("Diferente")
    senao
        escreval("Igual")
    fimse

Fimalgoritmo